name: Build & Test

on: pull_request
      
env:
  SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
  SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: chmod +x ./mvnw
      - run: ./mvnw install --settings ci-settings.xml --no-transfer-progress
      - run: bash <(curl -s https://codecov.io/bash)
